### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by ffurkanhas** [postaddictme/instagram-java-scraper#101]
I cant use scraper from an android project 

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process .../app/build/intermediates/transforms/desugar/debug/6.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/github/igorsuhorukov/dom/transform/DomTransformer.class
Error:com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process .../app/build/intermediates/transforms/desugar/debug/6.jar

**Comment by igor-suhorukov** [comment]
duplicate #92
