### ISSUE TITLE
Most of Account fields are null

### ISSUE THREAD

**Issue by twalther72** [postaddictme/instagram-java-scraper#104]
If I am scraping media with the code currently in the master then most of the fields related to account are null like:

    "fullName" : null,
    "isPrivate" : null,
    "isVerified" : null,
    "biography" : null,
    "externalUrl" : null,
    "followedBy" : null,
    "follows" : null,
    "blockedByViewer" : null,
    "countryBlock" : null,
    "externalUrlLinkshimmed" : null,
    "followedByViewer" : null,
    "followsViewer" : null,
    "hasBlockedViewer" : null,
    "hasRequestedViewer" : null,
    "profilePicUrl" : null,
    "profilePicUrlHd" : null,
    "requestedByViewer" : null,
    "connectedFbPage" : null,
    "isUnpublished" : null,
    "media" : null,

Is this a local problem or does someone else has the same issue?

**Comment by igor-suhorukov** [comment]
could you please provide more context information: API method that return this "null" fields?

**Comment by twalther72** [comment]
it is in

public abstract class PaginatedRequest<R, P extends RequestParameter>

public R requestInstagramResult(P requestParameters, int pageCount, PageInfo pageCursor) throws IOException 

the ModelMapper has the values but mapAccount delivers correct Account object with data. But then data get somewhere lost.

**Comment by igor-suhorukov** [comment]
@twalther72 you provide internal API, what is public API method of me.postaddict.instagram.scraper.Instagram?

**Comment by twalther72** [comment]
yes, me.postaddict.instagram.scraper.Instagram 

public PageObject<Media> getMedias(String username, int pageCount) throws IOException {

**Comment by igor-suhorukov** [comment]
@twalther72 it is not an issue. instagram-java-scraper use common object model and fill fields with data from json response. You can search for "owner" field value in getMedias response [as example](https://github.com/postaddictme/instagram-java-scraper/blob/master/src/test/resources/getMedias.json). Only ID owner field is available.

You can request [getAccountByUsername](https://github.com/postaddictme/instagram-java-scraper/blob/master/src/test/resources/getAccountByUsername_6e4a017e-e0ca-4512-9e96-48df0d486288.json)/getAccountById to get more details about account.
