### ISSUE TITLE
Caused by: java.io.NotSerializableException: me.postaddict.instagram.scraper.model.Media

### ISSUE THREAD

**Issue by tolgaduzenli** [postaddictme/instagram-java-scraper#105]
When I try to cache Media objects with Hazelcast, getting NotSerializableException.

com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'my serialized class object'

is this known problem ?

**Comment by igor-suhorukov** [comment]
It is not an issue of instagram-java-scriper. Use custom serializer http://docs.hazelcast.org/docs/3.0/manual/html/ch03s03.html
