### ISSUE TITLE
Instagram rate limited (HTTP 429 error)

### ISSUE THREAD

**Issue by arthur-barsegyan** [postaddictme/instagram-java-scraper#109]
Instagram sometimes responds with a 429 error (different behaviour from different IP's). We just getting likes and comments from **getMediaLikes()** and **getCommentsByMediaCode()**, respectively. 

Maybe community now some tricks and request limits per minute/hour etc?

**P.S** I think library have not flexible API because this methods (read above) get only 20 objects per request and for next request (for next 20 objects) create two requests: for first 20 objects (AGAIN!) and for next one. Why it was decided to do so?

**Comment by igor-suhorukov** [comment]
@arthur-barsegyan  limits are not statically defined - it is dynamics and based on user activity and behaviours [Team statement regarding Instagram's new artificial intelligence antispam system](https://github.com/mgp25/Instagram-API/issues/1741)

**Comment by arthur-barsegyan** [comment]
But what about last sentence?

**Comment by igor-suhorukov** [comment]
Hi @arthur-barsegyan 

getMediaLikes() and getCommentsByMediaCode() behaviour based on 
me.postaddict.instagram.scraper.request.PaginatedRequest#requestInstagramResult
I don't see any double http request per iteration.

**Comment by arthur-barsegyan** [comment]
@igor-suhorukov I mean about use this methods in general.
**Example:** 
I want receive all comments from Instagram media. 
In current revision `getCommentsByMediaCode()` get first page (first 20 comments) via PaginatedRequest and for the next page PaginatedRequest engine get first 20 comments again and after that a second one (but I always have first 20 comments!). 

**I think you should redesign this API.** 
For example, I receive PageObject from `getCommentsByMediaCode()` method and I want to pass this object on my next calls for getting appropriate results.

**Comment by igor-suhorukov** [comment]
@arthur-barsegyan thank you for example.

You can use public classes: GetCommentsByMediaCode, GetMediaLikesRequest

```
GetCommentsByMediaCode getCommentsByMediaCode = new GetCommentsByMediaCode(httpClient, mapper, delayHandler);
comments =  getCommentsByMediaCode.requestInstagramResult(new MediaCode(code), pageCount,
                    yourFirstPage);

GetMediaLikesRequest getMediaLikesRequest = new GetMediaLikesRequest(httpClient, mapper, delayHandler);
likes = getMediaLikesRequest.requestInstagramResult(new MediaCode(shortcode), pageCount, yourFirstPage);


```

**Comment by arthur-barsegyan** [comment]
@igor-suhorukov LOL 👍 
You absolutely right! Didn't think about it. 
But maybe it's not a so flexible decision in general ...

**Comment by igor-suhorukov** [comment]
> But maybe it's not a so flexible decision in general ...

Sure) But we try be as close as possible to [instagram-php-scraper](https://github.com/postaddictme/instagram-php-scraper) to port fixes from it
