### ISSUE TITLE
Get an error when calling instagram.getMediasByTag

### ISSUE THREAD

**Issue by jasoncartercs** [postaddictme/instagram-java-scraper#11]
When I call instagram.getMediasByTag, I get the following error:

me.postaddict.instagramscraper.exception.InstagramException: Response code is not equal 200. Something went wrong. Please report issue.
	at me.postaddict.instagramscraper.Instagram.getMediasByTag(Instagram.java:196)
	at Driver.main(Driver.java:101)

This used to work, but all of a sudden it stopped working.

**Comment by raiym** [comment]
@jasoncartercs yes. Instagram now requires auth tags and locations

https://github.com/postaddictme/instagram-php-scraper/issues/71

**Comment by raiym** [comment]
Library will support web login 

and maybe official API as well

**Comment by jasoncartercs** [comment]
Awesome thank you so much @raiym!!!!

Do you have a time estimate on when this library will support web login?

**Comment by raiym** [comment]
@jasoncartercs i just have released update with web login

**Comment by raiym** [comment]
@jasoncartercs or you need some different requirements?

**Comment by jasoncartercs** [comment]
@raiym I will check it out!

**Comment by raiym** [comment]
@jasoncartercs oh wait

**Comment by raiym** [comment]
I thought i am in php scraper thread

**Comment by raiym** [comment]
@jasoncartercs  at the weekends

**Comment by jasoncartercs** [comment]
@raiym No problem. I'll wait until then!

**Comment by raiym** [comment]
```java
Instagram instagram = new Instagram();
instagram.withCredentials("username", "password");
instagram.login();
instagram.getMediasByTag("hi");
```
