### ISSUE TITLE
Exception thrown when trying to scrap valid URL

### ISSUE THREAD

**Issue by farseev** [postaddictme/instagram-java-scraper#111]
public static String getMediaPageLinkByCodeMatcher() {
        return "https://www.instagram.com/p/{{code}}".replace("{{code}}", "[\\w-_]+");
    }

does not match a valid URL (those that are reposted to Twitter): e.g. this one: https://www.instagram.com/p/2QTKqqI3I7/

when calling getMediaByUrl()

**Comment by igor-suhorukov** [comment]
@farseev You provide invalid parameter - with "/" suffix. Try https://www.instagram.com/p/2QTKqqI3I7
It is not a bug, it is [additional check](https://github.com/postaddictme/instagram-java-scraper/issues/67) in code to avoid invalid service request.
