### ISSUE TITLE
getMediaByUrl

### ISSUE THREAD

**Issue by DiXL0f0S** [postaddictme/instagram-java-scraper#28]
I've tryied to execute this code
```
Instagram instagram = new Instagram();
media = instagram.getMediaByUrl("https://www.instagram.com/p/BGY0zB4r7X2/");
```
and get InstagramNotFoundException: Account with given username does not exist.

**Comment by xrevxp** [comment]
Instagram instagram = new Instagram();
media = instagram.getMediaByUrl("https://www.instagram.com/p/BGY0zB4r7X2");
