### ISSUE TITLE
testGetAccountById is broken

### ISSUE THREAD

**Issue by h31** [postaddictme/instagram-java-scraper#3]
Exception message:
`me.postaddict.instagramscraper.exception.InstagramException: Response code is not equal 200. Something went wrong. Please report issue.`
Actual response code is 405 (Method Not Allowed)

**Comment by raiym** [comment]
@h31 hello.
Thank you for creating issue. Instagram changed something and now this request doesnt work 

There is discussion about this issue (PHP Library): 

https://github.com/postaddictme/instagram-php-scraper/issues/45

**Comment by raiym** [comment]
Just FYI
This issue has been fixed in php scraper
