### ISSUE TITLE
Error: Account with given username does not exist.

### ISSUE THREAD

**Issue by jasoncartercs** [postaddictme/instagram-java-scraper#38]
Below is the error I get.

me.postaddict.instagramscraper.exception.InstagramNotFoundException: Account with given username does not exist.
	at me.postaddict.instagramscraper.Instagram.throwExceptionIfError(Instagram.java:326)
	at me.postaddict.instagramscraper.Instagram.getAccountById(Instagram.java:131)

**Comment by jasoncartercs** [comment]
Any update on this?

**Comment by igor-suhorukov** [comment]
@jasoncartercs please provide more context about issue: account username and/or account id

**Comment by igor-suhorukov** [comment]
this issue looks like "not reproduced"
