### ISSUE TITLE
Error 403 at login

### ISSUE THREAD

**Issue by sajjad-samadi** [postaddictme/instagram-java-scraper#43]
Well I'm trying to log in using this useful program, but I get 403 error. How can I solve the issue?

**Comment by rodrigae** [comment]
I am having the same issue

**Comment by Saddamko** [comment]
Hi! Where is no problems with authentication in this code now (10/25/2017). I also got error 403, but after as I'd rechecked my code, and put publicsuffixes.gz file in classpath, all is working fine. Trust me! And many-many thanks to author for free code! This is my first big java project and I get big experience. In additional I add jdbc support for storing account information in Oracle XE database.

**Comment by rodrigae** [comment]
Ok thank you!

Anthony
________________________________

**Comment by igor-suhorukov** [comment]
Hi @sajjad-samadi try new version of Instagram class with DelayHandler under the hood. Also correct connection with login [example in setUp() method](https://github.com/postaddictme/instagram-java-scraper/blob/master/src/test/java/me/postaddict/instagram/scraper/AuthenticatedInstaTest.java)

**Comment by igor-suhorukov** [comment]
@sajjad-samadi any updates?

**Comment by rodrigae** [comment]
haven't had this issue. in a while.

**Comment by igor-suhorukov** [comment]
@rodrigae sounds good!
