### ISSUE TITLE
Follow & Unfollow

### ISSUE THREAD

**Issue by rodrigae** [postaddictme/instagram-java-scraper#46]
Does the program currently handle that? I haven't been able to find it and make it work?

**Comment by rodrigae** [comment]
nvm, figure it out. Just pass the user id to this address once logged in, and it works.

https://www.instagram.com/web/friendships/486988862/follow/

https://www.instagram.com/web/friendships/user_id/follow/

**Comment by igor-suhorukov** [comment]
Hi @rodrigae ,
Follow & Unfollow not implemented yet.
 All supported and implemented function by login/password are enumerated in me.postaddict.instagram.scraper.AuthenticatedInstam

**Comment by rodrigae** [comment]
Thanks

**Comment by igor-suhorukov** [comment]
@asahi7 thank you for your contribution!
