### ISSUE TITLE
Парсер подписчиков

### ISSUE THREAD

**Issue by kovalchuk11** [postaddictme/instagram-java-scraper#47]
Приветствую! на хабре в комметах написали, что есть мысли как выгрузить подписчиков, поделитесь пожалуйста. знаю как в jsone на кого подписан юзер выгрузить, а подписчиков как выгрузить не знаю, есть мысль только selenium webdriver воспользоваться, но там больше 1000 подписчиков не выгрузится

**Comment by raiym** [comment]
@Tan4ek сделал в последнем PR, который я смерджил.

**Comment by raiym** [comment]
https://github.com/postaddictme/instagram-java-scraper/commit/7ad53f936b6495c622fa3ecd440bf19d7dcf5552
