### ISSUE TITLE
getLikes

### ISSUE THREAD

**Issue by dankarization** [postaddictme/instagram-java-scraper#54]
Is it possible to get all media likes?

**Comment by igor-suhorukov** [comment]
Only by private API

**Comment by raiym** [comment]
@dankarization it is possible. But for not available only in PHP library. 
Refer to PHP code: https://github.com/postaddictme/instagram-php-scraper/blob/e1ae14c7bc608dcb93dbb24c21d55c70cc792e76/src/InstagramScraper/Instagram.php#L423

**Comment by igor-suhorukov** [comment]
Thanks @raiym,
 I will re implement it in java as well

**Comment by igor-suhorukov** [comment]
implemented as me.postaddict.instagram.scraper.AuthenticatedInsta#getMediaLikes
