### ISSUE TITLE
Understand the limits of the lib api.

### ISSUE THREAD

**Issue by tpraizler** [postaddictme/instagram-java-scraper#58]
Hey!
Not sure if this is the right place for this, but wanted to understand the limits of using this API.
While requests don't need to be authenticated, how the limits apply? by ip?
If so what are the limits? 
Also, what are the limits for authenticated user (using the `login` method).
Looking in Instagram [documentation](https://www.instagram.com/developer/limits/) , the limits are described for requests that are using the access_token.

**Comment by igor-suhorukov** [comment]
@tpraizler limits are not statically defined - it is dynamics and based on user activity and behaviours [Team statement regarding Instagram's new artificial intelligence antispam system](https://github.com/mgp25/Instagram-API/issues/1741)
