### ISSUE TITLE
New collaborator

### ISSUE THREAD

**Issue by raiym** [postaddictme/instagram-java-scraper#61]
Since @igor-suhorukov actively contributing to the java library and have made last biggest refactor I decided to give write permissions to this repo to him. 
(I reserve the right to withdraw permission in the future) 

@igor-suhorukov thank you for active work.

**Comment by igor-suhorukov** [comment]
@raiym thank you for collaboration on instagram-java-scraper.
I will update documentation and do code refactoring to simplify project support
