### ISSUE TITLE
Issue with "ModelMapper.java"

### ISSUE THREAD

**Issue by Saddamko** [postaddictme/instagram-java-scraper#62]
In this code section:
return getUnmarshallerCache().computeIfAbsent(mappingFile, mapping -> ThreadLocal.withInitial(() -> getUnmarshaller(mapping)));
compiler show error *Cannot find symbol: getUnmarshallerCache().*

What is the getUnmarshallerCache() method? Where it is defined?
Tnx!

**Comment by igor-suhorukov** [comment]
Hi @Saddamko,

 getUnmarshallerCache() bytecode generated by https://projectlombok.org in compile time. If you try to compile it in IntelliJ Idea [install plugin](https://projectlombok.org/setup/intellij). In case of Eclipse [follow instruction](https://projectlombok.org/setup/eclipse)
```java
 @Getter(AccessLevel.PROTECTED)
    private final ConcurrentHashMap<String, ThreadLocal<Unmarshaller>> unmarshallerCache = new ConcurrentHashMap<>();
```

Gradle script build code without any issues.

**Comment by Saddamko** [comment]
Thanks!
It's right idea!
I'm use Netbean 8.2, and next instruction is help me:
_The Netbeans editor is compatible with lombok.
Add lombok.jar to the project libraries.
In the project properties, in the section Build – Compiling, check the 'Enable Annotation Processing in Editor' checkbox._

Saddly, I'm stuck with some another troubles (all project is fine, but with earlies releases I got more success:) After last update, just part of code is working.
For example, it's not working now:
instagram.addMediaComment("Bb605TuhIEG", "test");

run:
line 1:0 no viable alternative at character '<'
line 1:1 no viable alternative at character '!'
line 1:2 no viable alternative at character 'D'

Can You check this sample? (instagram.addMediaComment("Bb605TuhIEG", "test");)

**Comment by igor-suhorukov** [comment]
Thanks @Saddamko Vladimir! 
 Your error looks like response in html/xml (<!DOCTYPE>) is not in JSON format. May be you temporary blocked by service... For me all works fine on another posts.
 Could you please capture response in debug mode on line 
return mapper.mapMediaCommentResponse(responseBody.byteStream());
of class me.postaddict.instagram.scraper.Instagram

 We need to extend error handling for such cases in instagram-java-scraper

**Comment by igor-suhorukov** [comment]
@Saddamko this is not mapping issue. Try to configure http client in following way
```java
HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

OkHttpClient httpClient = new OkHttpClient.Builder()
        .addNetworkInterceptor(loggingInterceptor)
        .addInterceptor(new ErrorInterceptor())
        .cookieJar(new DefaultCookieJar(new CookieHashSet()))
        .build();
```

**Comment by igor-suhorukov** [comment]
Hi Vladimir @Saddamko , any updates?

**Comment by Saddamko** [comment]
Sorry for delay with my answer! It's OK now. For my shame, I did't know,  what is happened, but my code now is working w/o problems. Thanks!

**Comment by igor-suhorukov** [comment]
@Saddamko good news! In case of similar issue try to configure HttpClient with following interceptors:
``` java
OkHttpClient httpClient = new OkHttpClient.Builder()
        .addNetworkInterceptor(loggingInterceptor)
        .addInterceptor(new ErrorInterceptor())
```
