### ISSUE TITLE
CarouselResource always null

### ISSUE THREAD

**Issue by blaketanon** [postaddictme/instagram-java-scraper#75]
I'm assuming that a CarouselResource is a collection of images related to a parent Media (example https://www.instagram.com/p/BcaiZ8UFYyY/).  When I get media by 

`PageObject<Media> medias = instagram.getMedias(accountName, currentPage);`

the array is always null, is my assumption correct in what this should be?

**Comment by igor-suhorukov** [comment]
Hi @blaketanon 
>the array is always null, is my assumption correct in what this should be?
No, your  assumption is not correct. Server response for .getMedias() not return CarouselResource.
You can fetch CarouselResource only by .getMediaByCode() method
