### ISSUE TITLE
How get video url?

### ISSUE THREAD

**Issue by z0mb1ek** [postaddictme/instagram-java-scraper#78]
HI. 
I see no methods to get video url .mp4 from video posts

**Comment by z0mb1ek** [comment]
You can add {"java-attribute": "videoUrl","type": "java.lang.String","xml-path": "video_url/text()"} to media-by-url.json or I will add pull request for it =)

**Comment by igor-suhorukov** [comment]
Hi @z0mb1ek! Thank you for your bug report  and help with fix. I fixed this issue without PR)

**Comment by z0mb1ek** [comment]
big thx! should it be added also to CarouselResource?

**Comment by igor-suhorukov** [comment]
@z0mb1ek sure
