### ISSUE TITLE
Can I get my account's all media with paging?

### ISSUE THREAD

**Issue by ggamzzak** [postaddictme/instagram-java-scraper#79]
My instagram count is over 4000;

excuting getMedias(account,4000)... occur error;

but excuting getMedias(account,2000)... works.

Can I get my account's all media(4000)?

or... Can I get my account's all media with paging?

**Comment by igor-suhorukov** [comment]
Sure! 
just use public PageObject<Media> getMedias(String username, int **pageCount**)
