### ISSUE TITLE
Please update recent source for mvn or jitpack

### ISSUE THREAD

**Issue by ggamzzak** [postaddictme/instagram-java-scraper#81]
I got instagram-java-scraper with gradle

I'm using 'com.github.postaddictme:instagram-java-scraper:0.3.0'

Can you update recent source for mvn or jitpack?

I want to use 'public PageObject getMedias(String username, int pageCount)'

Please~~~

**Comment by igor-suhorukov** [comment]
Hi @ggamzzak 
This ticket is depends on #1

**Comment by ggamzzak** [comment]
Thank you for answer!
