### ISSUE TITLE
videoUrl is null...

### ISSUE THREAD

**Issue by ggamzzak** [postaddictme/instagram-java-scraper#84]
Sorry I took new issue tickets again, but I had searched repository text. After I received reply, I tried version 885979b instead of SNAPSHOT. But the result is the same.

log is...

```
PageObject(nodes=[Media(height=300, width=480, displayUrl=https://scontent-icn1-1.cdninstagram.com/vp/xxxxxx.jpg, videoUrl=null, displayResources=[DisplayResource(src=https://scontent-icn1-1.cdninstagram.com/vp/xxxxxx.jpg, width=150, height=150), isVideo=true, shouldLogClientEvent=null, trackingToken=null, mediaType=GraphVideo, id=16896257940972xxxxx, shortcode=BdywbUxxxxx, gatingInfo=null, caption=testxxxxxxxxxxx
, commentCount=896, commentPreview=null, firstComments=null, commentsDisabled=false, captionIsEdited=null, takenAtTimestamp=1515639206000, likeCount=63845, videoViewCount=null, firstLikes=null, location=null, owner=Account(...), viewerHasLiked=null, viewerHasSaved=null, viewerHasSavedToCollection=null, isAdvertising=null, carouselMedia=null, taggedUser=null, lastUpdated=Fri Jan 12 10:26:50 KST 2018)...
```

Above log is about video. but what I need is null, videoUrl, videoViewCount, carouselMedia... 
And how do I get the hitCount on non-video, photo...

**Comment by igor-suhorukov** [comment]
Try to debug your application and view http response from server for each of request. instagram-java-scraper parse service response and not produce new unknown values. Is response contains video_url, video_view_count, edge_sidecar_to_children ?

>And how do I get the hitCount on non-video, photo...
likeCount available for GraphImage/GraphSidecar/GraphVideo. I don't know any hitCount in service response for getMedias(...)

getMedias use URL https://www.instagram.com/{{username}}/?__a=1&max_id=

So try getMediaByCode for one of your video/carousel post...

**Comment by chrismpalmer** [comment]
I am also having this problem video URL is null even though isVideo == true?

**Comment by igor-suhorukov** [comment]
@chrismpalmer just use getMediaByCode and read my previous comment
