### ISSUE TITLE
Instagram API deprecation

### ISSUE THREAD

**Issue by tpraizler** [postaddictme/instagram-java-scraper#95]
This is more of a question.
Does this mean the web api will be deprecated too?
https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

**Comment by igor-suhorukov** [comment]
There are 3 types of API : official Instagram API that covered by this article, web site endpoints - non official API used by web site and this client, private mobile app API - endpoints for mobile applications. 
Second one is most unstable - base of instagram-java-scraper library.

I don't know) I think that web api will be changed more frequent then official API

**Comment by igor-suhorukov** [comment]
> I see. so you don't expect problems with the API based on that article?

correct! I am expect another issues with website API

**Comment by tpraizler** [comment]
Got it. Thanks!
