### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by Mehrshadow** [postaddictme/instagram-java-scraper#99]
since importing all the classes to our project, most of them are full of errors and many methods missing from several classes
like: 
in class "GraphQlResponse" many methods like "getPayload" are missed that are used in project
I don't know if this is just our issue or others also

please help us using code

thanks in advance

**Comment by igor-suhorukov** [comment]
Hi @Mehrshadow 
Setup lombok plugin and enable annotation processor in IDE options

https://github.com/postaddictme/instagram-java-scraper#ide-lombok-plugin
